name : First Workflow
on:
  push: 
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first Github Actions Wrokflows!" 

      - name: Checkout repository
        uses: actions/cache@v4.2.4

      - name: List repository files
        run : ls -la

